### ISSUE TITLE
Consumes lots of energy

### ISSUE THREAD

**Issue by bfintal** [blaise-io/live-reload#10]
I'm running the latest Chrome, and I have 20 tabs open (using The Great Discarder extension too, nothing else). I turned on Live Reload, watching on for only `*://localhost:888/*` (which is turned on in only 2 tabs) and my macBook's fans are going crazy. Checking my battery, it displays the browser consuming significant energy when Live Reload is on.

Once I disable Live Reload extension, things go quiet again.

**Comment by blaise-io** [comment]
@bfintal Thanks for reporting.

How many source files were matched, approximately?  
Which browser are you using?  

This addon is quite heavy when monitoring lots of source files, it fetches the file every N seconds and this includes hashing the entire file contents. Maybe there's some optimizations possible.

**Comment by blaise-io** [comment]
Inactive
