### ISSUE TITLE
long cooldown period ?

### ISSUE THREAD

**Issue by oglops** [blaise-io/live-reload#11]
It seems to have a long cooldown period after it trigger a reload(works perfect the first time), then after around 30s it seems to detected there are something to monitor. 

It only works when there is a 1 number next to extension icon, then you change file on disk, it reloads itself,  then the 1 is gone, at this moment updating file on disk has no effect, it does not reload, after 30s, the 1 appears again, then it works again..  you just need to wait another 30s.

browser : google chrome

**Comment by blaise-io** [comment]
@oglops  Did any file change in those 30 seconds?

**Comment by blaise-io** [comment]
@oglops this is possibly fixed in 1.8.0 which has a different mechanism for detecting files to monitor.
