### ISSUE TITLE
[question] How to reload on backend change (not css/js)?

### ISSUE THREAD

**Issue by tomsquest** [blaise-io/live-reload#16]
Hi @blaise-io ,

It is documented that, yes, live-reload can reload the page on **backend** change. And I did success to do that some weeks/months ago But as of today, I am not able to reload on backend change (not css, nor js).

#### How to reproduce

1. Setup extension on `localhost:4200/*`, also tried with an additional `localhost:4200/search/products` (see screenshot)
1. Change backend page (rendered html)
1. No reload occurs.

Config:

![image](https://user-images.githubusercontent.com/365778/77527354-41677f00-6e8c-11ea-9770-4d2b8d2a9747.png)

#### Infos

- Firefox 74.0
- live-reload 1.8.0

**Comment by blaise-io** [comment]
You cannot reload on a backend change, but the backend change usually results in an updated source file URL and you could monitor that file.

**Comment by tomsquest** [comment]
Hi Blaise,

Yes, that was I am aiming at : reloading when the source change.

For info, I have a Go backend that produce html, which is reloaded on change (`inotifywait` magic).

In the screenshot above, I tried with `http://localhost:4200/search/products/` (which was the url of my browser). But this was not working. Same with a trailing `*`, with or without the trailing `/`.
Is there something special to do ?

Thanks a lot.

**Comment by blaise-io** [comment]
So you want to update the page when the page itself is updated?

Does Host URL: `http://localhost:4200/*`, Source file URL: `http://localhost:4200/*` work for you?

**Comment by tomsquest** [comment]
No, the page is not updated on html change with this config. Css is.

- There is the badge with value `2` corresponding to the 2 css files loaded with the page.
- Here are the network call after a page reload, 3 resources (one html, 2 css) :
![image](https://user-images.githubusercontent.com/365778/77989400-00092080-731f-11ea-91c0-bd28fa259262.png)
- Updated version to 1.8.1 and accepted the permission change (and restarted Firefox)

Is there a way to report the monitored resources in Firefox ?

Thanks Blaise.

**Comment by blaise-io** [comment]
I probably broke monitoring the page itself in 1.8.0, I’ll fix that this week.

**Comment by blaise-io** [comment]
@tomsquest I fixed this in Live Reload 1.8.2. If a source URL matches the host URL the page will monitor itself. Can you confirm it works?

**Comment by tomsquest** [comment]
Hi @blaise-io ,

It works with 1.8.2 !

Thanks a lot for the work (I read a bit of the code and there is much more that I thought !).

Regarts,
Tom
