### ISSUE TITLE
not working : chrome + localhost

### ISSUE THREAD

**Issue by nervusdm** [blaise-io/live-reload#17]
Rules url :
http://localhost/tds/*
script url: 
http://localhost/tds/*.css
(tried others .css urls too)

How can I debug it ?

Tried it on FF and Chrome

**Comment by blaise-io** [comment]
Debugging is explained on https://chrome.google.com/webstore/detail/live-reload/jcejoncdonagmfohjcdgohnmecaipidc and https://addons.mozilla.org/addon/live-reload/, it's different per browser. It should help you understand which files are monitored.
