### ISSUE TITLE
Firefox Permission Requirements, Remove "Access your data for all websites"

### ISSUE THREAD

**Issue by gregelenbaas** [blaise-io/live-reload#19]
Really appreciate your plugin. Was wondering if the readme could clarify why the Firefox Extension requests permission to "Access your data for all websites." If it's not needed it should be removed. 

Thanks for your work!

**Comment by blaise-io** [comment]
The monitoring is done by intercepting all resources loaded by the host URL and requires access to any website. I don't know which websites you're going to monitor so I cannot limit the websites up front. Inline reloading also requires access to all possible websites.

Ideally the web extension would request access to only the website you want to monitor, but this is not possible at the moment in web extensions APIs.

Finally, I appreciate any skepticism you may have. If you don't trust me or my web extension it's best to inspect the source code and compile the web extension yourself.

**Comment by blaise-io** [comment]
I will implement this when browser offer a lazy way to ask accessing data for a website. Currently this is not in the web extension APIs.
