### ISSUE TITLE
Live Reload not available in Chrome Web Store

### ISSUE THREAD

**Issue by rik-smeets** [blaise-io/live-reload#20]
The [link to the Chrome Web Store](https://chrome.google.com/webstore/detail/live-reload/jcejoncdonagmfohjcdgohnmecaipidc), as referenced from the README, appears to be broken.

Could the extension be re-uploaded to the Chrome Web Store? Thanks!

**Comment by blaise-io** [comment]
Google took it down because it was missing a description. I submitted for review, may "up to two weeks".

**Comment by rik-smeets** [comment]
It's available again, thanks!
