### ISSUE TITLE
Add extension to Microsoft Edge Add-ons store

### ISSUE THREAD

**Issue by rik-smeets** [blaise-io/live-reload#21]
The new Microsoft Edge is based on Chromium, just like Google Chrome. Edge does have its own [Add-ons store](https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home?hl=en-US). Although adding extensions from the Chrome Web Store is possible too (after allowing), it has some advantages to also make the live-reload extension available in the Microsoft Edge Add-ons store.

If you're okay with it, I could do this for you. I have a Microsoft developer account with which I can submit extensions to the Edge Add-ons store. It would be published under my name, I unfortunately can't change that, but I'd of course provide links to this Github page. Thanks for letting me know what you think.

**Comment by blaise-io** [comment]
Thanks @rik-smeets, I will port it to Edge in a few days.

**Comment by blaise-io** [comment]
> Microsoft is reviewing your submission right now​

**Comment by blaise-io** [comment]
https://microsoftedge.microsoft.com/addons/detail/live-reload/oajnffmbmcjoipibgecmgbdlnhboajfh
