### ISSUE TITLE
I cannot get it to work. I am having wordpress on local host and I am changing my custom theme files, css and js.

### ISSUE THREAD

**Issue by Lovor01** [blaise-io/live-reload#23]
Host: https://altius.duckdns.org/*
Source files: https://altius.duckdns.org/wp-content/themes/altius/*.css*
https://altius.duckdns.org/wp-content/themes/altius/*/*.js*

Example of file being changed: https://altius.duckdns.org/wp-content/themes/altius/style.css?ver=1.0.0

How can I debug it with about:devtools-toolbox?type=extension&id=live-reload%40blaise%2Eio?

**Comment by Lovor01** [comment]
It started working when I added css path explicitly, i.e. https://altius.duckdns.org/wp-content/themes/altius/style.css?ver=1.0.0

**Comment by blaise-io** [comment]
@Lovor01  I cannot reproduce this issue. Can you help me by answering a few questions?

- Did you check "Reload stylesheets without reloading the page"?
- Was the CSS loaded using `<link>` or `@import`?
- Did the bubble show the expected count of monitored source files?
- Which browser are you using?

**Comment by Lovor01** [comment]
> 
> 
> @Lovor01 I cannot reproduce this issue. Can you help me by answering a few questions?
> 
>     * Did you check "Reload stylesheets without reloading the page"?
> I tried both
>     * Was the CSS loaded using `<link>` or `@import`?
> <link>
>     * Did the bubble show the expected count of monitored source files?
> No, when it was not working, there were no bubbles
>     * Which browser are you using?
Tried Firefox developer version.

It started working, I do not know what was the problem.

**Comment by sajadabasi** [comment]
I've been having the same problem didn't work with CSS with `?v=1.1`

**Comment by sajadabasi** [comment]
@Lovor01 Is the issue resolved?

**Comment by Lovor01** [comment]
I believe the problem was final asterisk in Host URK to catch all subpages under main page - like this:
http://www.dummy.org/*

**Comment by Lovor01** [comment]
> 
> 
> @Lovor01 Is the issue resolved?

Yes, thanks
