### ISSUE TITLE
Add custom third-side css

### ISSUE THREAD

**Issue by HDDen** [blaise-io/live-reload#24]
Hello! What about adding option to inject third-side css?
For example, I used this extension to write and test additional styles for site. I need to edit my own css; so, I inject localhosted .css, then monitoring it by your extension. Css is editable in IDE. When I save, it automatically updates on page.
It's be cool to do both part of operation in one extension

**Comment by blaise-io** [comment]
Sorry, this is out of scope for this extension. Perhaps there are other extensions that allow you to do this, in which case ive Reload should pick up any files injected.
